# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-runner-label:
    runs-on: ubuntu-latest
    steps:
      - uses: devops-actions/load-runner-info@v1.0.9
        id: load-runner-info-org
        with: 
          accessToken: ${{ secrets.GH_Action_PAT }}
          organization: Fork-on-the-Table-Collective
      - uses: actions/github-script@v7
        id: get_runner_label
        env:
          RUNNERS: ${{ steps.load-runner-info-org.outputs.runners }}
          ACTOR: ${{ github.actor }}
          RUNNER_PARAMS: ${{ vars.RUNNER_PARAMS }}
        with:
          script: |
              const runners=JSON.parse(process.env.RUNNERS)
              const runner_params=JSON.parse(process.env.RUNNER_PARAMS)
              const actor=process.env.ACTOR
              const actor_runner = Object.entries(runner_params).filter(([key, value]) => value.actor === actor).map(([key, value]) => key);
              const labels = runners.filter(runner => runner.status=="online" && runner.name==actor_runner).map(runner => runner.labels[3].name)
              const label = labels.length>0?labels[0]:""
              console.log(label)
              return label
      - name: result
        run: echo ${{ steps.get_runner_label.outputs.result }}
